# use v2.x API to allow `mem_limit` option
version: "2.4"

services:
  oxd_server:
    image: gluufederation/oxd-server:4.2.0_dev
    environment:
      - GLUU_CONFIG_CONSUL_HOST=consul
      - GLUU_SECRET_VAULT_HOST=vault
      - GLUU_PERSISTENCE_TYPE=${PERSISTENCE_TYPE}
      - GLUU_PERSISTENCE_LDAP_MAPPING=${PERSISTENCE_LDAP_MAPPING}
      - GLUU_LDAP_URL=ldap:1636
      - GLUU_COUCHBASE_URL=${COUCHBASE_URL}
      - GLUU_COUCHBASE_USER=${COUCHBASE_USER}
      - APPLICATION_KEYSTORE_PATH=/opt/oxd-server/conf/oxd-server.keystore
      - APPLICATION_KEYSTORE_PASSWORD_FILE=/etc/gluu/conf/app_keystore_password
      - APPLICATION_KEYSTORE_CN=oxd_server
      - ADMIN_KEYSTORE_PATH=/opt/oxd-server/conf/oxd-server.keystore
      - ADMIN_KEYSTORE_PASSWORD_FILE=/etc/gluu/conf/admin_keystore_password
      - ADMIN_KEYSTORE_CN=oxd_server
      - GLUU_SERVER_HOST=$DOMAIN
      - GLUU_REDIS_URL=redis:6379
      - GLUU_REDIS_TYPE=STANDALONE
      - STORAGE=gluu_server_configuration
    container_name: oxd-server
    restart: unless-stopped
    mem_limit: 500M
    labels:
      - "SERVICE_IGNORE=yes"
    extra_hosts:
      - "${DOMAIN}:${HOST_IP}"
    volumes:
      # - ./volumes/oxd-server/certs:/etc/certs
      - ./vault_role_id.txt:/etc/certs/vault_role_id
      - ./vault_secret_id.txt:/etc/certs/vault_secret_id
