# use v2.x API to allow `mem_limit` option
version: "2.4"
services:
  casa:
    image: gluufederation/casa:4.2.0_dev
    environment:
      - GLUU_CONFIG_CONSUL_HOST=consul
      - GLUU_SECRET_VAULT_HOST=vault
      - GLUU_OXAUTH_BACKEND=oxauth:8080
      - GLUU_PERSISTENCE_TYPE=${PERSISTENCE_TYPE}
      - GLUU_PERSISTENCE_LDAP_MAPPING=${PERSISTENCE_LDAP_MAPPING}
      - GLUU_LDAP_URL=ldap:1636
      - GLUU_COUCHBASE_URL=${COUCHBASE_URL}
      - GLUU_COUCHBASE_USER=${COUCHBASE_USER}
      - GLUU_OXD_SERVER_URL=oxd_server:8443
    extra_hosts:
      - "${DOMAIN}:${HOST_IP}"
    container_name: casa
    volumes:
      - ./vault_role_id.txt:/etc/certs/vault_role_id
      - ./vault_secret_id.txt:/etc/certs/vault_secret_id
      - ./couchbase.crt:/etc/certs/couchbase.crt
      - ./casa.json:/etc/gluu/conf/casa.json
      - ./couchbase_password:/etc/gluu/conf/couchbase_password
    restart: unless-stopped
    labels:
      - "SERVICE_NAME=casa"
