version: "3"

services:
  consul:
    image: consul
    command: agent -server -bootstrap -ui
    hostname: consul-1
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
    container_name: consul

  nginx:
    image: gluufederation/nginx:3.1.2_dev
    environment:
      - GLUU_KV_HOST=consul
      - GLUU_OXAUTH_BACKEND=oxauth:8080
      - GLUU_OXTRUST_BACKEND=oxtrust:8080
    ports:
      - "80:80"
      - "443:443"
    container_name: nginx

  ldap:
    image: gluufederation/opendj:3.1.2_dev
    environment:
      - GLUU_KV_HOST=consul
      - GLUU_LDAP_INIT=true
      - GLUU_LDAP_INIT_HOST=ldap
      - GLUU_LDAP_INIT_PORT=1636
    container_name: ldap

  oxauth:
    image: gluufederation/oxauth:3.1.2_dev
    environment:
      - GLUU_KV_HOST=consul
      - GLUU_LDAP_URL=ldap:1636
    container_name: oxauth

  oxtrust:
    image: gluufederation/oxtrust:3.1.2_dev
    environment:
      - GLUU_KV_HOST=consul
      - GLUU_LDAP_URL=ldap:1636
    extra_hosts:
      - "${DOMAIN}:${HOST_IP}"
    container_name: oxtrust
