# use v2.x API to allow `mem_limit` option
version: "2.4"

services:
  consul:
    image: consul
    command: agent -server -bootstrap -ui
    hostname: consul-1
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
    container_name: consul
    restart: unless-stopped
    volumes:
      - ./volumes/consul:/consul/data
    labels:
      - "SERVICE_IGNORE=yes"
    restart: unless-stopped

  vault:
    container_name: vault
    image: vault:1.0.1
    command: vault server -config=/vault/config
    volumes:
      - ./volumes/vault/config:/vault/config
      - ./volumes/vault/data:/vault/data
      - ./volumes/vault/logs:/vault/logs
      - ./vault_gluu_policy.hcl:/vault/config/policy.hcl
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_REDIRECT_INTERFACE=eth0
      - VAULT_CLUSTER_INTERFACE=eth0
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_LOCAL_CONFIG={"backend":{"consul":{"address":"consul:8500","path":"vault/"}},"listener":{"tcp":{"address":"0.0.0.0:8200","tls_disable":1}}}
    restart: unless-stopped
    depends_on:
      - consul
    labels:
      - "SERVICE_IGNORE=yes"

  registrator:
    image: gluufederation/registrator:dev
    command: registrator -internal -cleanup -resync 30 -retry-attempts 5 -retry-interval 10 consul://consul:8500
    container_name: registrator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    restart: unless-stopped
    depends_on:
      - consul

  nginx:
    image: gluufederation/nginx:4.0.0_dev
    environment:
      - GLUU_CONFIG_CONSUL_HOST=consul
      - GLUU_SECRET_VAULT_HOST=vault
    ports:
      - "80:80"
      - "443:443"
    container_name: nginx
    restart: unless-stopped
    labels:
      - "SERVICE_IGNORE=yes"
    volumes:
      - ./vault_role_id.txt:/etc/certs/vault_role_id
      - ./vault_secret_id.txt:/etc/certs/vault_secret_id

  oxauth:
    image: gluufederation/oxauth:4.0.0_dev
    environment:
      - GLUU_CONFIG_CONSUL_HOST=consul
      - GLUU_SECRET_VAULT_HOST=vault
      - GLUU_PERSISTENCE_TYPE=ldap
      - GLUU_PERSISTENCE_LDAP_MAPPING=default
      - GLUU_LDAP_URL=ldap:1636
      - GLUU_COUCHBASE_URL=couchbase
    extra_hosts:
      - "${DOMAIN}:${HOST_IP}"
    container_name: oxauth
    volumes:
      - ./volumes/oxauth/custom/pages:/opt/gluu/jetty/oxauth/custom/pages
      - ./volumes/oxauth/custom/static:/opt/gluu/jetty/oxauth/custom/static
      - ./volumes/oxauth/custom/libs:/opt/gluu/jetty/oxauth/custom/libs
      - ./volumes/oxauth/custom/i18n:/opt/gluu/jetty/oxauth/custom/i18n
      - ./volumes/oxauth/logs:/opt/gluu/jetty/oxauth/logs
      - ./vault_role_id.txt:/etc/certs/vault_role_id
      - ./vault_secret_id.txt:/etc/certs/vault_secret_id
    mem_limit: 1536M
    restart: unless-stopped
    labels:
      - "SERVICE_NAME=oxauth"
      - "SERVICE_8080_CHECK_HTTP=/oxauth/.well-known/openid-configuration"
      - "SERVICE_8080_CHECK_INTERVAL=15s"
      - "SERVICE_8080_CHECK_TIMEOUT=5s"

  oxtrust:
    image: gluufederation/oxtrust:4.0.0_dev
    environment:
      - GLUU_CONFIG_CONSUL_HOST=consul
      - GLUU_SECRET_VAULT_HOST=vault
      - GLUU_OXAUTH_BACKEND=oxauth:8080
      - GLUU_PERSISTENCE_TYPE=ldap
      - GLUU_PERSISTENCE_LDAP_MAPPING=default
      - GLUU_LDAP_URL=ldap:1636
      - GLUU_COUCHBASE_URL=couchbase
    extra_hosts:
      - "${DOMAIN}:${HOST_IP}"
    container_name: oxtrust
    volumes:
      - ./volumes/oxtrust/custom/pages:/opt/gluu/jetty/identity/custom/pages
      - ./volumes/oxtrust/custom/static:/opt/gluu/jetty/identity/custom/static
      - ./volumes/oxtrust/custom/libs:/opt/gluu/jetty/identity/custom/libs
      - ./volumes/oxtrust/custom/i18n:/opt/gluu/jetty/identity/custom/i18n
      - ./volumes/oxtrust/logs:/opt/gluu/jetty/identity/logs
      - ./volumes/shared-shibboleth-idp:/opt/shared-shibboleth-idp
      - ./vault_role_id.txt:/etc/certs/vault_role_id
      - ./vault_secret_id.txt:/etc/certs/vault_secret_id
    mem_limit: 1536M
    restart: unless-stopped
    labels:
      - "SERVICE_NAME=oxtrust"
      - "SERVICE_8080_CHECK_HTTP=/identity/restv1/scim-configuration"
      - "SERVICE_8080_CHECK_INTERVAL=15s"
      - "SERVICE_8080_CHECK_TIMEOUT=5s"
      - "APP_NAME=oxtrust"
