# use v2.x API to allow `mem_limit` option
version: "2.4"

services:
  key_rotation:
    image: gluufederation/key-rotation:4.0.0_dev
    environment:
      - GLUU_CONFIG_CONSUL_HOST=consul
      - GLUU_SECRET_VAULT_HOST=vault
      - GLUU_LDAP_URL=ldap:1636
      - GLUU_KEY_ROTATION_INTERVAL=2  # interval to regenerate keys if needed (in hours)
      - GLUU_KEY_ROTATION_CHECK=30    # interval to check whether keys should be checked (in seconds)
    volumes:
      - ./vault_role_id.txt:/etc/certs/vault_role_id
      - ./vault_secret_id.txt:/etc/certs/vault_secret_id
    container_name: key-rotation
    restart: unless-stopped
    labels:
      - "SERVICE_IGNORE=yes"
